"""Generate FIT5215_A1_methodology.ipynb -- the methodology + iteration-path report.

Kept as a script so the notebook can be regenerated after any correction, rather than
hand-edited JSON drifting away from the numbers in experiment_history_*.csv.
"""
import io
import json

cells = []


def md(text):
    cells.append({'cell_type': 'markdown', 'metadata': {},
                  'source': text.strip('\n').splitlines(keepends=True)})


def code(text):
    cells.append({'cell_type': 'code', 'metadata': {}, 'execution_count': None,
                  'outputs': [], 'source': text.strip('\n').splitlines(keepends=True)})


# ----------------------------------------------------------------- 1. header
md(r"""
# Assignment 1 — 20-class animal image classification

**Final Kaggle submissions**

| pick | file | public LB | what it is |
|---|---|---|---|
| 1 | `submission_ens_V2PEVAPtemp.csv` | **0.98196** | DINOv2 ViT-L/14 pseudo1 + EVA-02 Large pseudo1 |
| 2 | `submission_ens_V2PV3Ptemp.csv` | 0.98132 | DINOv2 ViT-L/14 pseudo1 + DINOv3 ViT-L/16 pseudo1 |

Both are temperature-matched equal-weight blends with no parameter fitted on the leaderboard.
They share V2P and differ in the second member, which comes from a different pretraining family
in each: EVA-02 (masked image modelling, then ImageNet-22k/1k supervised fine-tuning) in pick 1,
DINOv3 (self-distillation, never supervised) in pick 2. On the leaderboard the two are a
statistical tie. Reasoning in §6.

**Disclosure.** The EVA-02 line did not pass its own pre-registered gate: its base model scored
0.96915 against a 0.9700 bar. Continuing to the distillation stage was a decision taken *after*
seeing that score, and it is labelled as such (§5.5). Nothing in that line was fitted on the
leaderboard, and its blend was admitted by a local screen fixed before the blend was computed.

Progression over the project: 0.740 → 0.97342 (single ConvNeXt-V2-L) → 0.97566 (first working
blend) → 0.98132 → **0.98196**.

**Academic integrity.** No test label was ever assigned, reviewed, corrected or verified by a
human or by an external AI. Every number below comes from a forward pass of a model trained
in this repository. Pseudo-labelling uses only the competition's explicitly permitted route:
labels generated by our own trained models. An earlier phase of this project did manually
review low-confidence test predictions; that work was found to violate the rules, was fully
retracted, and nothing downstream of it survives in either final pick.

This is not asserted, it is checked — `integrity_audit.py` traces every probability feeding
either submission back to a model forward pass, including the root of the distillation chain,
and is run below.
""")

md(r"""
## 0. Reproducing the two submissions, and auditing their provenance

`reproduce.py` rebuilds both CSVs from the cached per-model test probabilities and checks them
row-for-row. Full retraining (~21 GPU-hours) is documented in §7.
""")

code(r"""
!python reproduce.py
""")

md(r"""
`integrity_audit.py` then verifies where every one of those probabilities came from. The
chain matters: pick 1's members were distilled from teachers, which were themselves blends of
earlier models, and so on back to a root teacher. The audit reconstructs each teacher from its
stated members and checks that the root reproduces a **pre-correction** submission row-for-row
— which is what establishes that the retracted manual-correction work never entered the
lineage.

It also scans every source file for executable references to the quarantined directory or to
the corrections-contaminated teacher file. That check is deliberately strict — it looks at
executable lines only, not comments — and it caught a real latent hazard: a retired 2026-09-10
patch script that would have written a fallback to the contaminated teacher back into the
notebook. That script produced no artefact and nothing descends from it, but it has been
neutralised (it now refuses to run) and archived.
""")

code(r"""
!python integrity_audit.py
""")

# ----------------------------------------------------------------- 2. problem
md(r"""
## 1. The problem, and what actually made it hard

| | |
|---|---|
| Train | 9,466 labelled JPEGs at original resolution (mostly 300–640px), roughly class-balanced (368–512 per class), squashed to 64x64 with LANCZOS to match the test set |
| Test | 11,681 unlabelled 64x64 JPEGs (q75, 4:2:0) |
| Split | public LB = 80% (~9,345 images), private = 20% (~2,336); **ranking is private only** |
| Budget | 100 submissions/day, single RTX 3080 (10 GB) |

Two properties of the data drove every decision.

**A domain gap.** The training set is 100% photographs. The test set is roughly 80%
photographs and 20% *renditions* — paintings, drawings, sculptures, line art. Nothing in the
training data teaches the model what a painted duck looks like. This was diagnosed early and
is the single largest error source; it is what the external data, and ultimately the choice
of pretraining prior, exist to attack.

**64 pixels is genuinely lossy, and unevenly so.** A controlled ablation on a clean checkpoint
found accuracy already falling at 48px (99.30% -> 98.52%) and collapsing by 16px (81.82%), and
the six confusion-cluster classes (birds/ducks/chickens, cats/dogs, bottles/vases/lipsticks…)
degrade consistently faster than the rest — a 10.4pt gap by 16px. Renditions are 3–4x more
resolution-fragile than photographs. So the domain gap and the resolution limit compound:
renditions carry less usable fine-grained signal at 64px than photos do.
""")

# ----------------------------------------------------------------- 3. pipeline
md(r"""
## 2. Pipeline

Four stages. Stages 1–2 are shared by every model in the project; 3–4 are what the iteration
explored.

**1. External rendition data.** DomainNet *painting* + ImageNet-R, mapped to the 20 classes,
pushed through the exact test degradation (`('squash', 'PIL:LANCZOS')` -> 64px -> the test
set's own JPEG quantisation tables) so the external images match the test spectrum rather
than merely depicting the right object. Mixed into every batch at a fixed ratio via a
floor-balanced draw. `prepare_external.py`, `filter_external_spectrum.py`,
`extract_imagenet_r.py`.

A label-mapping audit here mattered more than any hyperparameter: DomainNet `bottlecap` turned
out to be a mosaic-art genre — 538 of 709 candidate "bottles" were fish and portrait mosaics
with no bottle in them — and `zebra` was 48% of the "horses" pool. Both were removed and the
pools rebuilt.

**2. Base supervised stage.** A pretrained backbone fine-tuned at 192px (196px for the ViT) on
real + external data. RandomJpeg(0.3, 55–95), TrivialAugmentWide, RandomResizedCrop(0.60–1.0),
RandomErasing(0.25), MixUp(0.2)/CutMix(1.0) on half the batches, label smoothing 0.1, EMA
0.999, cosine schedule with 2 warmup epochs, 16 epochs, AMP. Checkpoint on best validation.

**3. Self-distillation (Noisy Student).** A *fresh* student, re-initialised from pretrained
weights, trained on real + external + pseudo-labelled test images. Pseudo-labels come from an
**external teacher** — the best blend available at that time — not from the student's own
predictions. Selection is argmax with confidence >= 0.7; pseudo rows carry weight 0.5.
Exactly one round.

**4. Inference and blending.** 6-view TTA (3 scales x horizontal flip). Blends are
temperature-matched equal-weight averages with no parameter fitted on the leaderboard (§5.4).
""")

# ----------------------------------------------------------------- 4. lineage
md(r"""
## 3. The model lineage

Every leaderboard result, from the first baseline to the final pick. The retracted
manual-correction submissions from 09-09 to 09-11 are excluded — they are not part of any
lineage that reaches the final picks.
""")

code(r"""
import csv, io
import pandas as pd

# Submissions produced by the retracted manual-correction work, or downstream of its
# contaminated teacher. Excluded from every table in this report: they are not part of any
# lineage reaching the final picks, and they must not be reported as results.
RETRACTED = {'31 tier-A edits', '78 self-consistent edits', 'submission_corr_B.csv',
             'submission_A3.csv', 'submission_2seed_corr.csv', 'submission_corr_cnv2L.csv',
             'submission_corr_cnv2L_r3.csv', 'submission_tta18_corr.csv'}

rows = list(csv.DictReader(io.open('experiment_history_leaderboard.csv', encoding='utf-8')))
scored = [r for r in rows if r['kaggle_public'] not in ('PENDING', 'NOT SUBMITTED', '')]
legit = [r for r in scored if r['submission'] not in RETRACTED]

df = pd.DataFrame({'date': [r['date'] for r in legit],
                   'submission': [r['submission'] for r in legit],
                   'public_LB': [float(r['kaggle_public']) for r in legit]})
print(f'{len(scored)} scored submissions, of which {len(scored)-len(legit)} are retracted '
      f'and excluded -> {len(df)} legitimate')
print(f'range {df.public_LB.min():.5f} .. {df.public_LB.max():.5f}\n')
print('Top 10 legitimate submissions:')
print(df.sort_values('public_LB', ascending=False).head(10).to_string(index=False))
print('\nProgression of the best legitimate score over time:')
best = df.sort_values(['date']).assign(best=lambda d: d.public_LB.cummax())
print(best.groupby('date').best.max().to_string())
""")

md(r"""
### The models that matter, and how each was built

| tag | model | teacher it was distilled from | public LB |
|---|---|---|---|
| **A** | ConvNeXt-V2-L (FCMAE), 192px, pseudo1 | `teacher_clean_test` (0.96499-era) | 0.97342 |
| **C** | ConvNeXt-V2-L, 256px, pseudo1 | same | 0.97203 |
| **D3** | ConvNeXt-L **DINOv3** prior, pseudo1 | A ⊗ C logit 1:2 (0.97566) | 0.97171 |
| **KD** | ConvNeXt-V2-L, **soft-label** KD | ACD3temp (0.97673) | 0.97524 |
| **V2** | **DINOv2 ViT-L/14** reg4, base only | — (never distilled) | 0.97363 |
| **V2P** | DINOv2 ViT-L/14, pseudo1 | KDCD3temp (0.97716) | 0.97950 |
| **V3T** | **DINOv3 ViT-L/16**, base only | — (never distilled) | **0.97556** |
| **V3P** | DINOv3 ViT-L/16, pseudo1 | V2P (0.97950) | — |
| **EVA** | **EVA-02 Large** (MIM on Merged-38M, IN-22k/1k fine-tuned), base only | — (never distilled) | 0.96915 |
| **EVAP** | EVA-02 Large, pseudo1 | V2P + V3P (0.98132) | **0.98132** |

Each generation's teacher is the previous generation's best blend. That chain —
0.96499 → 0.97566 → 0.97673 → 0.97716 → 0.97950 → 0.98132 — is the backbone of the project.

Worth noting what **V3T** is: a model that scored 0.97556 having *never used the test set at
all* — no pseudo-labels, no distillation. It beat every earlier distilled model except one,
purely on the strength of its pretrained representation plus the external rendition data. It
was a member of the earlier pick 2, replaced on 2026-09-17 (§6).

And **EVAP**: the weakest ViT base model (0.96915) became, after one round of distillation, a
single model scoring exactly what the blend that taught it scored — the largest distillation
gain in the project (+1.22pt).
""")

# ----------------------------------------------------------------- 5. methodology
md(r"""
## 4. Methodology: how decisions were made

This is the part that generalises beyond this dataset.

### 4.1 Every local metric failed, and they failed in the same direction

Four independent attempts to build a local gate, all of which had to be abandoned:

| instrument | how it failed |
|---|---|
| Validation accuracy (1,419 imgs) | **Saturated.** ~99% for both the best model and one 0.085pt worse. Worse than useless: FixMatch had the **highest validation ever recorded here (0.9922)** and the **lowest leaderboard score of any distilled model (0.96926)** — anti-predictive by 0.42pt. |
| sketch-val | **Circular.** Reinstating the XDoG `sketch_prob` augmentation raised sketch-val +15pt; a non-circular held-out rendition check moved +0.15pt, i.e. noise. It was measuring the model learning the metric's own transform. |
| Reserved rendition set (772 imgs) | **Inverts across the base/pseudo boundary.** It ranked a 256px base model 4.4pt *above* its own distilled version (p<0.001); Kaggle ranked the distilled one 0.85pt *better*. |
| Distribution-matched estimator | **Failed calibration.** Scored photos and renditions separately over 6,758 held-out images and reweighted 80/20 to match the test mix. SE 0.20pt, better than the leaderboard's — and it ranked the *worst* of four models first, winning on *both* strata, so no reweighting could fix it. |

**They share one cause.** The distillation stage trains on pseudo-labelled **test images**. Its
entire benefit is adaptation to the actual test distribution, and no held-out proxy contains
those images. So every local set ranks base >= distilled while Kaggle says the opposite.

**What survived.** The reserve metric is reliable for *direction* in **same-stage** comparisons
only (base vs base, or pseudo1 vs pseudo1). It went 4-for-4 there, including correctly calling
the DINOv2 base model before its leaderboard score existed, and 6-for-6 on significant gaps by
the end (§5.5). Its magnitudes stay uncalibrated — the ratio to the leaderboard has ranged from
about 1:1 to 6:1. It is used below only in that regime. A *non-significant* reserve gap is not
evidence of parity: EVA-02's base was −0.39pt on the reserve (p = 0.77) and a significant
−0.64pt on the leaderboard.

### 4.2 Treating the leaderboard as a measuring instrument

With local gates gone, the leaderboard is the instrument — so it needs error bars. Two
submissions differing on only `k` rows are not two independent samples; the difference is the
net win/loss on those `k` rows:

    net wins   = delta x 9,345
    LB rows    ~ 0.8k          (the public split is 80% of the test set)
    win rate   = (LB rows + net) / (2 x LB rows)

A result counts as a **signal** only at `k >= 60` **and** win rate `>= 60%`; otherwise it is a
**tie**. Rearranged, the threshold is `delta >= 0.16k/9345`, which has a consequence that is
easy to get wrong: **a change touching more rows must win by proportionally more.** At k=60 a
signal needs 0.103pt; at k=172 it needs 0.294pt. Several results that looked like gains were
correctly recorded as ties by this test.
""")

code(r"""
def verdict(new, base, k, name):
    d = new - base
    net = d * 9345
    lb_rows = 0.8 * k
    win = (lb_rows + net) / (2 * lb_rows)
    need = 0.16 * k / 9345
    tag = 'SIGNAL' if (k >= 60 and win >= 0.60) else ('tie (k<60)' if k < 60 else 'TIE')
    print(f'{name:38s} k={k:4d}  delta {100*d:+.3f}pt  net {net:+6.1f}  '
          f'win-rate {100*win:5.1f}%  needs {100*need:.3f}pt  -> {tag}')

print('Decisions this test produced:\n')
verdict(0.97673, 0.97534,  62, 'add DINOv3 to the blend')
verdict(0.97524, 0.97342, 172, 'soft-KD student replaces A?')
verdict(0.97790, 0.97716,  60, 'add DINOv2 base to the blend')
verdict(0.97950, 0.97363, 187, 'DINOv2: distillation vs its own base')
verdict(0.97908, 0.97950,  92, 'blending KD into the best single model')
verdict(0.98132, 0.96915, 249, 'EVA-02: distillation vs its own base')
verdict(0.98196, 0.97950,  93, 'adding EVAP to V2P')
verdict(0.98196, 0.98132,  80, 'the two final picks')
""")

md(r"""
Distillation on the DINOv2 trunk is a decisive signal (+0.587pt, 68.3%), while blending the
FCMAE-based KD student into the result is a tie — a weaker member from a weaker prior. The last
three lines are the EVA-02 line: distillation +1.22pt, adding its student to V2P a signal, and
the two final picks a tie with each other.

### 4.3 The ensemble rule, and the correction that broke it

An early recorded belief that "ensembling does not work on this problem" turned out to be
wrong; it had only ever been tested by mixing a strong model with a clearly weaker one, or
with a same-architecture seed twin. The working rule for most of the project was
two-dimensional — a member must clear **both** comparable strength (within ~0.2pt of the
anchor) **and** decorrelation (~2% disagreement with the anchor):

| member | standalone | vs anchor | disagreement | effect |
|---|---|---|---|---|
| B trio_bal030 | 0.97257 | −0.08 | 0.99% | **hurts** — strong but too similar |
| C res256 | 0.97203 | −0.14 | 1.87% | **helps** +0.22pt |
| E thr060 | 0.97054 | −0.29 | 1.09% | **hurts** — too similar |
| FixMatch | 0.96926 | −0.42 | 2.10% | **hurts** — decorrelated but too weak |
| D res256 base | 0.96350 | −0.99 | 2.29% | **hurts** — far too weak |
| D3 DINOv3 | 0.97171 | −0.17 | 2.10% | **helps** +0.139pt (signal) |
| V2 DINOv2 base | 0.97363 | +0.02 | 2.29% | **helps** |

Seven for seven — and then it failed.

**CORRECTION. The disagreement-rate half of that rule is wrong, and one pair of experiments
disproves it cleanly.** Two members were each blended into the same anchor (V2P, 0.97950):

| member added to V2P | raw disagreement | blend result |
|---|---|---|
| KD | 1.61% | 0.97908 — **tie**, slightly negative |
| V3T | **1.50%** | **0.98089 — SIGNAL, +0.139pt** |

Added to the same anchor, the member with the **lower** disagreement produced a leaderboard
**signal** and the higher-disagreement one a **tie**. Raw disagreement is therefore not a
sufficient criterion; it was a proxy that happened to hold while every member came from the
same pretraining prior.

**What the evidence supports instead is complementary errors, measured directly.** A blend whose
held-out rendition accuracy **exceeds both of its members** — rather than landing between them —
is combining models that are right on different images. KD, an FCMAE model, is weak on
renditions like every FCMAE model (88.86% against V2P's 93.01%), so its disagreements with V2P
sit on the same hard rows and averaging cannot correct them.

| blend | renditions | vs best member | leaderboard vs V2P alone |
|---|---|---|---|
| V2P + V3T | 93.78% | **+0.77pt** | +0.139pt — signal |
| V2P + V3P | 94.43% | +0.13pt | +0.182pt — signal |
| V2P + EVAP | 94.04% | +1.04pt | +0.246pt — signal (screened before it was submitted, §5.5) |

All three blends exceeded both members, all were reported before submitting, and all produced a
leaderboard signal — the project's first local screen to predict a blend gain, 3 for 3 on
**direction**. It does **not** track magnitude: a +0.13pt exceedance gave +0.182pt and a +0.77pt
exceedance gave +0.139pt. This screen was used to reject four further blend candidates without
spending a submission, and five more EVAP blends were not submitted because they moved too few
rows to be distinguishable from the best file (§5.5).

**CORRECTION (2026-09-15).** An earlier version of this section explained the V2P + V3T gain as
V3T being "worse on renditions but +0.47pt better on photos", and said the smaller exceedance
"predicted the weaker leaderboard outcome (a tie)". Both were wrong. The +0.47pt was inferred
from a V3T-vs-V2 leaderboard gap that is itself a statistical tie (k = 205, win rate 55.5%, a
signal needs 0.351pt), and a labelled photo holdout built later measured that photo gap at
−0.32pt, also noise. The "tie" compared that blend against a different baseline; against V2P
alone both blends are signals. Which stratum carries the complementarity is not established.

A third variable, unaffected by the correction: **sharpness**. Geometric averaging beats
arithmetic, and weight should go toward the *less confident* member, because the sharper model
dominates the argmax regardless of merit. "Sharp **and** weak" is the worst possible
combination — FixMatch's mean top-1 confidence was 0.9568 against A's 0.8943, which is why
even a 0.25 weight cost 0.107pt.

### 4.4 Blend construction, with nothing fitted on the leaderboard

Weights tuned against public-LB feedback overfit the public split, which is exactly the wrong
thing to do when ranking is private-only. So blends use one construction with no free
parameter: solve a temperature per member so all members share the reference member's mean
top-1 confidence, then average with **equal** weight.

This is not a workaround — it is a third route to the same correction that up-weighting and
geometric averaging achieve, and it was validated as such: `AClogit1to2` (weights fitted on
the LB) scored 0.97566 and `ACtemp` (temperature-matched, nothing fitted) scored 0.97534,
inside noise of each other. Both final picks use this construction.
""")

code(r"""
from blend_temp import blend, load

for pick, tags in [('pick 1', ['V2P', 'EVAP']), ('pick 2', ['V2P', 'V3P'])]:
    _, temps, matched = blend(tags, mode='arithmetic')
    ref = matched[0].max(1).mean()
    print(f'{pick}: temperatures solved so each member matches {tags[0]}\'s sharpness')
    for tag, T in zip(tags, temps):
        print(f'    {tag:>3}  T = {T:.4f}   mean top-1 confidence '
              f'{load(tag).max(1).mean():.4f} -> {ref:.4f}')
print('\nThe temperature is solved by bisection against the members\' own confidences.')
print('No weight, threshold or temperature here was chosen by looking at a leaderboard score.')
""")

# ----------------------------------------------------------------- 6. what won
md(r"""
## 5. Why the final model wins — and it is not what we expected

The last three days tested four mechanisms. Only one class of them worked.

| mechanism | outcome |
|---|---|
| FixMatch (consistency semi-supervision) | line closed, −0.64pt standalone |
| Soft-label KD (full teacher distribution instead of argmax) | best single model at the time (0.97524), but a **tie** in the blend |
| **Change the pretraining prior: DINOv3** | +0.139pt **signal** into the blend |
| **Change the pretraining prior: DINOv2 ViT-L** | **0.97363 at base stage, 0.97950 distilled** |

The first two are changes *inside* one pretraining prior — a different loss, a better teacher —
and both hit the same wall. Both changes *of* prior went through it.

**CORRECTION — it is mostly the architecture; the prior's share is unresolved.** An earlier
version of this report attributed the jump to the pretraining prior, and a later version split
it 78% architecture / 22% prior. A later run separated the two variables, because the first
comparison changed both at once (DINOv3-on-ConvNeXt vs DINOv2-on-ViT):

| model | architecture | prior | renditions | public LB |
|---|---|---|---|---|
| DINOv3 ConvNeXt-L | ConvNeXt | DINOv3 | 89.64% | 0.96264 |
| **DINOv3 ViT-L/16** | **ViT** | DINOv3 | **92.88%** | **0.97556** |
| DINOv2 ViT-L/14 | ViT | DINOv2 | 93.78% | 0.97363 |

**The architecture effect is confirmed on the leaderboard:** same DINOv3 prior, ConvNeXt → ViT,
+1.29pt. **The prior comparison is not:** DINOv2 ViT vs DINOv3 ViT at the base stage is a
statistical tie on the leaderboard (+0.193pt at k = 205, win rate 55.5%, where a signal needs
0.351pt), so the 78/22 split — which rested on that pair — is withdrawn. The supportable
statement is: *a self-supervised ViT* is what suits this problem; which self-supervised recipe
is better was not resolved.

### 5.1 The advantage was won at the base stage, not by distillation
""")

code(r"""
for name, base, ps1 in [('ConvNeXt-V2-L 256', 0.96350, 0.97203),
                        ('ConvNeXt-L DINOv3', 0.96264, 0.97171),
                        ('DINOv2 ViT-L/14  ', 0.97363, 0.97950),
                        ('EVA-02 Large     ', 0.96915, 0.98132)]:
    print(f'  {name}   base {base:.5f} -> pseudo1 {ps1:.5f}   distillation gain {100*(ps1-base):+.2f}pt')
""")

md(r"""
DINOv2's distillation gain is the **smallest** of the first three. Its lead was already there
before any test image was used: its base model beat every previous base by 1.01pt and beat *A*,
a fully distilled model. So for DINOv2 the result is about the pretrained representation, not
about our distillation recipe.

**EVA-02, added after the picks were first locked (§5.5), is the exception, and a large one:**
the weakest ViT base (0.96915), the largest distillation gain (+1.22pt), ending level with the
best blend available at the time. "The advantage is won at the base stage" therefore holds for
DINOv2, not as a general rule — a supervised-fine-tuned MIM trunk gained far more from adapting
to the test distribution than any lineage scored at both stages before it.

### 5.2 The mechanism is the rendition domain, and the arithmetic closes

The reserve set is 772 held-out rendition images — the domain the test set is ~20% made of,
and the documented error concentration. This is a same-stage comparison, the one regime where
that metric is trustworthy.
""")

code(r"""
import numpy as np

r = np.load('bench/reserve_preds.npz')
lab = r['lab']
members = {'C  pseudo1': r['pc'],
           'A  pseudo1': r['pa'],
           'D3 pseudo1': np.load('bench/dinov3ps1_reserve_prob.npy'),
           'V2 base   ': np.load('bench/dinov2vitl_base_reserve_prob.npy'),
           'V2 pseudo1': np.load('bench/dinov2vitlps1_reserve_prob.npy')}
print('accuracy on 772 held-out RENDITIONS')
for n, p in members.items():
    print(f'  {n}  {100*(p.argmax(1)==lab).mean():6.2f}%')

V, A = members['V2 pseudo1'].argmax(1), members['A  pseudo1'].argmax(1)
print(f'\n  paired:  V2 right / A wrong = {int(((V==lab)&(A!=lab)).sum())}, '
      f'A right / V2 wrong = {int(((A==lab)&(V!=lab)).sum())}')

edge = (V == lab).mean() - (A == lab).mean()
print(f'\n  V2ps1 - A on renditions        = {100*edge:+.2f}pt')
print(f'  test set ~20% renditions       ~ {0.20*11681:.0f} images')
print(f'  predicted effect on full test  = {100*edge*0.20:+.2f}pt')
print(f'  OBSERVED on the leaderboard    = {100*(0.97950-0.97342):+.2f}pt')
""")

md(r"""
A prediction made from a 772-image held-out set lands within 0.01pt of the observed 0.61pt
leaderboard gap. For **this pair**, the rendition domain accounts for essentially the entire
advantage: a self-supervised ViT transfers to non-photographic domains in a way FCMAE (masked
reconstruction over ImageNet photographs) does not, and that is precisely the error bucket
this dataset leaves open.

**CORRECTION — whether this generalises is unresolved.** An earlier version of this report
presented DINOv3 ViT-L vs DINOv2 ViT-L as a counterexample: worse on renditions (92.88% vs
93.78%) yet better on the leaderboard (0.97556 vs 0.97363), with an "implied photo gap" of
+0.47pt, and counted it against the reserve metric's record (4-for-4 → 4-for-5). That claim is
withdrawn. The leaderboard gap it rests on is a statistical tie (k = 205, win rate 55.5%, a
signal needs 0.351pt), so there is no inversion to explain and no implied photo gap, and the
reserve's record on real leaderboard signals stays 4-for-4. A labelled photo holdout built
afterwards (3,124 DomainNet `real` test-split photos) measured that pair's photo gap at
−0.32pt (p = 0.31) — also noise.

What still holds: the reserve set is 100% renditions, so it measures *one stratum*, not the
leaderboard, and the V2P-vs-A decomposition above is a result about that pair rather than a
general law.

### 5.3 Why blending a *weaker* model into the best one loses

The strength half of §4.3's rule survives the correction, and this is where it bites. Once V2P
reached 0.97950, every model available *except the other self-supervised ViT* was 0.43–0.78pt
weaker — beyond the cutoff bracketed between −0.14pt (helps) and −0.42pt (hurts). Worse, they
are weakest *precisely where V2P's advantage lives*: 85–90% on renditions against its 93%. So
on the rows that carry the edge, the strong model is outvoted by weaker ones.
""")

code(r"""
import numpy as np

r = np.load('bench/reserve_preds.npz')
lab = r['lab']
V = np.load('bench/dinov2vitlps1_reserve_prob.npy').argmax(1)
others = [r['pa'].argmax(1), r['pc'].argmax(1),
          np.load('bench/dinov3ps1_reserve_prob.npy').argmax(1),
          np.load('bench/dinov2vitl_base_reserve_prob.npy').argmax(1)]
wrong = np.sum([o != lab for o in others], axis=0)

overruled = int(((V == lab) & (wrong >= 3)).sum())
rescued = int(((V != lab) & (wrong <= 1)).sum())
print(f'  V2ps1 right, >=3 of 4 others wrong  (equal blend OVERRULES it) : {overruled}')
print(f'  V2ps1 wrong, >=3 of 4 others right  (equal blend RESCUES it)   : {rescued}')
print(f'  net cost of averaging on renditions: {overruled-rescued} of {len(lab)} '
      f'= {100*(overruled-rescued)/len(lab):.2f}pt')
print('\n  -> observed: V2P+KD blend 0.97908 vs the single model 0.97950')
""")

md(r"""
### 5.4 Distillation moves answers, not ability

The final experiment was designed to transfer DINOv2's advantage into the ConvNeXt lineage: a
ConvNeXt-V2-L student distilled from V2P (0.97950) — a genuine +0.28pt teacher upgrade. Two
predictions were registered before it ran, and both held:

- It agrees with its teacher on **99.0% of test rows** (1.01% disagreement) — a lossy copy,
  below even the similarity level that made member B harmful. It cannot join the ensemble.
- Its rendition accuracy is **88.86% — identical to the earlier ConvNeXt student, and 4.15pt
  below its own teacher.**

Those two facts together are the finding. The student reproduces the teacher's decisions on
the *test* images it was trained on, then falls straight back to FCMAE-level accuracy on
renditions it has never seen. **A capability that lives in the pretrained representation
cannot be distilled into an architecture that lacks it.** This explains why "upgrade the
teacher" saturates within a prior, and it closes the loop with §5.2: the rendition domain is
both the entire source of V2's advantage and the one part that does not transfer.

The submission for this run was **not** made — it could neither improve on what it copied nor
join the ensemble, so it would only have measured copying loss.
""")

md(r"""
### 5.5 After the picks were first locked: four more experiments, one success

The picks were first locked on 2026-09-14 (V2P + V3P, V2P + V3T). Four experiments followed,
each with its gate written down before any result. Every base model used the identical recipe
(196px or 192px, flat 2e-5, 16 epochs), so only the pretrained weights differ.

| experiment | what changed | base public | outcome |
|---|---|---|---|
| LP-FT on DINOv3 ViT-L | 2-epoch linear probe before the fine-tune | 0.97310 (vs 0.97556) | closed — reserve +0.65pt and photo holdout +0.67pt locally, leaderboard −0.25pt |
| SigLIP 2 ViT-L/16 | language-supervised prior | 0.94268 | gate (≥ 0.9700) failed by 2.7pt; closed |
| Web-SSL DINO ViT-L | DINOv2's recipe on 2B uncurated web images | 0.94236 | gate failed by 2.8pt; closed |
| **EVA-02 Large** | MIM on Merged-38M + ImageNet-22k/1k fine-tune | **0.96915** | gate **missed by 0.085pt**; continued by a post-hoc decision |

**What they settle.** Web-SSL has DINOv2's exact recipe and size and scored 3.1pt lower, so the
curated pretraining data is part of what made DINOv2 work here, not only the objective. SigLIP
2's failure is consistent with language supervision transferring poorly under this recipe, but
its slow start also fits a learning rate too small for that trunk, so the cause is not
established. For both, the reserve predicted the direction before submission; the
reserve-to-leaderboard ratio was about 1:1 for these large gaps against ~4:1 earlier, which is
why a reserve gap is never converted into a leaderboard number.

**The EVA-02 line, and the decision taken in it.** Its base missed the gate by about ten images
(0.34 SE). The pre-registered rule said stop, and stopping was the recommendation. The decision
taken after seeing the score was to run distillation anyway, with every downstream rule
unchanged: teacher = the V2P + V3P blend (0.98132), threshold 0.7, weight 0.5, and a blend CSV
only if it moved ≥ 60 rows from the best file *and* exceeded both members on the reserve. There
was a precedent — DINOv3's distilled ConvNeXt had missed its bar by 0.12 SE, was blended anyway,
and paid.

| | public | paired verdict |
|---|---|---|
| EVAP alone | 0.98132 | vs its own base +1.22pt: **signal**; vs V2P: tie |
| V2P + EVAP — reserve 94.04% (+1.04pt over both members), k = 80 | **0.98196** | vs V2P alone: **signal**; vs V2P + V3P: tie |

**Blending is now saturated.** Five further EVAP blends were fixed in advance: EVAP + V3P,
EVAP + V3T, and the three- and four-member combinations with V2P. Four of them exceeded their
members on the reserve, but every one moved only 42–54 rows from 0.98196 — below the 60 rows at
which a leaderboard difference can read as anything but a tie. None was submitted.
""")

# ----------------------------------------------------------------- 7. picks
md(r"""
## 6. Choosing the two final submissions

Ranking is on the private 20% — 2,336 images, where 0.1pt is 2.3 images and the standard error
is about 0.32pt. The public lead is not a safety margin.

**CORRECTION to an earlier version of this report.** It argued for a second pick with an
"orthogonal failure mode", accepting a 0.34pt lower score to get one. That reasoning was
wrong: it implicitly assumed the public and private splits differ in some way a diverse
ensemble could hedge against. **They do not — the split is a random 20%.** Any systematic
weakness of a model appears in both halves equally and is therefore already visible in the
public score. The only thing separating the two halves is sampling noise, so the question is
purely: how often does pick 2 beat pick 1 on 2,336 images, and by how much?

Two submissions differing on `k` rows differ on about `0.2k` private rows; if those rows are
coin flips, the net has SD `sqrt(0.2k)` against an expected gap of `delta x 2336`:
""")

code(r"""
from math import sqrt, pi, exp, erf

PRIVATE = 2336

def second_pick_value(delta_pt, k, name):
    m = 0.20 * k                                   # rows differing on the private split
    sd = sqrt(m)                                   # SD of the net, if those rows are coin flips
    mu = delta_pt / 100 * PRIVATE                  # expected images pick 1 is ahead by
    Phi = lambda x: 0.5 * (1 + erf(x / sqrt(2)))
    phi = lambda x: exp(-x * x / 2) / sqrt(2 * pi)
    gain = sd * phi(mu / sd) - mu * Phi(-mu / sd)  # E[max(0, pick2 - pick1)]
    print(f'  {name:38s} gap {delta_pt:.3f}pt  differing rows ~{m:4.0f}  '
          f'P(pick2 wins) {100*Phi(-mu/sd):4.1f}%   E[gain] {100*gain/PRIVATE:.3f}pt')

print('Value of the second pick, with V2P+EVAP (0.98196) as pick 1, on the private 2,336 images:\n')
second_pick_value(0.064,  80, 'V2P+V3P  (0.98132)   <- chosen')
second_pick_value(0.064,  49, 'EVAP alone (0.98132)')
second_pick_value(0.107,  92, 'V2P+V3T  (0.98089)')
second_pick_value(0.406, 117, 'KDCD3V2temp (0.97790)  "orthogonal"')
""")

md(r"""
A pick 0.4pt behind essentially never wins, so the "orthogonal" option is worth an order of
magnitude less than a near-tied one; and among near-tied candidates, the one differing on more
rows has more chances to come out ahead — EVAP alone is as strong as V2P + V3P on the public
split but too similar to pick 1 (49 rows) to be worth as much. The final pair, changed on
2026-09-17 from V2P + V3P / V2P + V3T:

| | file | public | second member |
|---|---|---|---|
| pick 1 | `submission_ens_V2PEVAPtemp.csv` | **0.98196** | EVAP — EVA-02 Large, distilled from the V2P + V3P blend |
| pick 2 | `submission_ens_V2PV3Ptemp.csv` | 0.98132 | V3P — DINOv3 ViT-L, distilled from V2P |

The two are a measured tie (Δ 0.064pt at k = 80, win rate 54.7%), so the higher public score
takes pick 1. They share V2P and differ in a second member from a different pretraining family.
Replacing the previous pair raised the expected private score by roughly one image — positive
and free, not a margin.

Neither pick contains a parameter fitted on the public leaderboard. Pick 1 descends from the
EVA-02 line whose base gate was overridden after the fact (§5.5).
""")

# ----------------------------------------------------------------- 8. repro
md(r"""
## 7. Full reproduction

**Fast path** (seconds, no GPU):

```bash
python reproduce.py        # rebuilds both CSVs from cached model outputs, checks row-for-row
python integrity_audit.py  # traces every input back to a model forward pass
```

**Full path** (~21 GPU-hours on one RTX 3080). Each stage writes the `bench/*_test_prob.npy`
that later stages consume, so the order matters.

```bash
# --- data ------------------------------------------------------------------
python extract_imagenet_r.py            # ImageNet-R parquet -> imagenet_r_ext/<class>/
python prepare_external.py              # DomainNet painting, degraded to the test spectrum
python filter_external_spectrum.py      # domain self-check; must pass
python prepare_external.py --append imagenet_r_ext
python filter_external_spectrum.py
python _make_eval_holdout.py            # reserve the eval set BEFORE any training draw

# --- generation 1: the ConvNeXt-V2 line (notebook) -------------------------
jupyter nbconvert --execute --to notebook --inplace FIT5215_v8.ipynb   # -> A, and C at 256px

# --- generation 2: DINOv3 prior --------------------------------------------
DINO_TAG=dinov3cnl DINO_LR=2e-5 DINO_LAYER_DECAY=1.0 python dinov3_base_train.py
DINO_TAG=dinov3ps1 DINO_TEACHER=bench/teacher_AC12.npy python dinov3_pseudo_train.py

# --- generation 3: soft-label KD (teacher = A (x) C (x) D3) ----------------
python _prep_soft_kd.py                 # patches the notebook; teacher_ACD3temp_test.npy
jupyter nbconvert --execute --to notebook --inplace FIT5215_v8.ipynb   # -> KD

# --- generation 4: DINOv2 ViT-L/14 -----------------------------------------
python blend_temp.py --members KD C D3 --mode arithmetic \
    --out submission_ens_KDCD3temp.csv --save-prob bench/ens_KDCD3temp_test_prob.npy
#   then renormalise that array to bench/teacher_KDCD3temp.npy

DINO_TAG=dinov2vitl  DINO_BACKBONE=vit_large_patch14_reg4_dinov2.lvd142m \
  DINO_SIZE=196 DINO_TTA=168,196,224 DINO_POOL=avg DINO_GRAD_CKPT=1 \
  DINO_BATCH=20 DINO_LR=2e-5 DINO_LAYER_DECAY=1.0 python dinov3_base_train.py

DINO_TAG=dinov2vitlps1 DINO_BACKBONE=vit_large_patch14_reg4_dinov2.lvd142m \
  DINO_SIZE=196 DINO_TTA=168,196,224 DINO_POOL=avg DINO_GRAD_CKPT=1 \
  DINO_BATCH=20 DINO_TEACHER=bench/teacher_KDCD3temp.npy python dinov3_pseudo_train.py
#   -> V2P, a member of BOTH picks

# --- generation 5: DINOv3 ViT-L/16 -----------------------------------------
#   patch16 divides 160/192/224, so the default sizes apply unchanged.
DINO_TAG=dinov3vitl  DINO_BACKBONE=vit_large_patch16_dinov3.lvd1689m \
  DINO_POOL=avg DINO_GRAD_CKPT=1 DINO_BATCH=20 \
  DINO_LR=2e-5 DINO_LAYER_DECAY=1.0 python dinov3_base_train.py
#   -> V3T (0.97556, never distilled); in the earlier pick 2, not in the final picks

#   renormalise bench/dinov2vitlps1_test_prob.npy to bench/teacher_V2P.npy, then:
DINO_TAG=dinov3vitlps1 DINO_BACKBONE=vit_large_patch16_dinov3.lvd1689m \
  DINO_POOL=avg DINO_GRAD_CKPT=1 DINO_BATCH=20 \
  DINO_TEACHER=bench/teacher_V2P.npy python dinov3_pseudo_train.py
#   -> V3P, the second member of PICK 2

python blend_temp.py --members V2P V3P --mode arithmetic \
    --out submission_ens_V2PV3Ptemp.csv --save-prob bench/teacher_V2PV3P.npy   # [PICK 2] + next teacher

# --- generation 6: EVA-02 Large --------------------------------------------
python eva02_load_check.py              # every pretrained tensor loads, except the 1000-class head

DINO_TAG=eva02l DINO_BACKBONE=eva02_large_patch14_448.mim_m38m_ft_in22k_in1k \
  DINO_SIZE=196 DINO_TTA=168,196,224 DINO_GRAD_CKPT=1 \
  DINO_BATCH=20 DINO_LR=2e-5 DINO_LAYER_DECAY=1.0 python dinov3_base_train.py
#   -> EVA base, 0.96915: missed the 0.9700 gate; not needed to rebuild the picks

DINO_TAG=eva02lps1 DINO_BACKBONE=eva02_large_patch14_448.mim_m38m_ft_in22k_in1k \
  DINO_SIZE=196 DINO_TTA=168,196,224 DINO_GRAD_CKPT=1 \
  DINO_BATCH=20 DINO_TEACHER=bench/teacher_V2PV3P.npy python dinov3_pseudo_train.py
#   -> EVAP, the second member of PICK 1 (post-hoc continuation, section 5.5)

# --- pick 1, admitted by the pre-registered screen ---------------------------
python candidate_report.py --tag eva02lps1 --blend-with dinov2vitlps1 \
    --write submission_ens_V2PEVAPtemp.csv                               # [PICK 1]
python blend_temp.py --members V2P EVAP --mode arithmetic \
    --out check_pick1.csv --verify submission_ens_V2PEVAPtemp.csv       # 0 rows differ
python evap_blend_screen.py             # five further EVAP blends: none passes, none submitted
```

### Files

| file | role |
|---|---|
| `dinov3_base_train.py` | base-stage trainer; backbone/size/TTA/pooling via `DINO_*` env vars |
| `dinov3_pseudo_train.py` | distillation stage; teacher via `DINO_TEACHER` |
| `blend_temp.py` | temperature-matched blending; also rebuilds every historical blend |
| `FIT5215_v8.ipynb` | the ConvNeXt-V2 line (models A, C, KD) |
| `_prep_soft_kd.py` | patches the notebook for soft-label KD |
| `prepare_external.py`, `filter_external_spectrum.py`, `extract_imagenet_r.py` | external data |
| `_make_eval_holdout.py`, `_heldout_split.py` | reserve the evaluation set before training |
| `candidate_report.py` | candidate report and the pre-registered blend screen; wrote pick 1 |
| `evap_blend_screen.py` | the five further EVAP blends, screened and not submitted |
| `eva02_load_check.py` | verifies EVA-02 loads every pretrained tensor except the classifier head |
| `webssl_timm.py` | Web-SSL weights renamed into timm; imported by the base trainer (that line closed) |
| `reproduce.py` | rebuilds and verifies both final submissions |
| `integrity_audit.py` | traces every input back to a model forward pass; 13 checks |
| `experiment_history_runs.csv`, `experiment_history_leaderboard.csv` | every run, every submission |

A note on the trainer filenames: `dinov3_*_train.py` were written for the DINOv3 experiment and
then generalised to any timm backbone through environment variables. They train the DINOv2
models too. The names were kept so the recorded commands stay literally reproducible.
""")

# ----------------------------------------------------------------- 9. negatives
md(r"""
## 8. What was ruled out

Negative results, with what each cost and what it settled. Several of these were more useful
than the wins.

| tried | result |
|---|---|
| Manual review of low-confidence test predictions | **Prohibited.** Fully retracted and quarantined regardless of measured effect; no surviving artefact depends on it. |
| Same-architecture seed ensembling | 0.99% disagreement — init diversity is not architectural diversity. Scored below the single model. |
| Wider TTA (18-view vs 6-view) | No change; extra views' row edits net to zero. |
| `sketch_prob` augmentation | +15pt on sketch-val, +0.15pt on a non-circular check. The metric was circular. |
| 256px / 288px input | 256 distilled scored below 192 distilled; 1.3x compute. |
| Class-prior rebalancing (EM, global and within-group) | −0.5 to −1.1pt, four separate attempts. |
| Rank averaging across images | −3.4pt. Destroys the within-image comparability argmax needs. |
| Power averaging on a geometric blend | Mathematically a no-op — a positive power is monotone, so argmax cannot move. Confirmed to 5 decimals. |
| Graph label propagation on kNN features | Killed for 5 GPU-minutes by measuring it on the labelled reserve first: 3–4 rows broken per row fixed, monotone in alpha. Low-confidence rows sit in an anchor-poor region — the propagation source is weakest exactly where help is needed. |
| Model soup (weight averaging) | Works (0.97342 from three ingredients at or below 0.97257) but loses to probability blending by 0.22pt: a soup collapses several models into one decision boundary, destroying the diversity that makes blending pay. |
| FixMatch | Ran clean, best validation in the project, worst distilled leaderboard score. |
| ConvNeXt-V2-**Huge** (658M) | 0.95869 — capacity is not the bottleneck; data and prior are. |
| `train_on_all_data` | −0.53pt; it disables best-epoch selection. |
| Layer-wise LR decay on a self-supervised trunk | −1.95pt of reserve accuracy against a flat 2e-5 control. The "SSL trunks need a bigger step" intuition is wrong at this data scale. |
| LP-FT (linear probe, then fine-tune) on DINOv3 ViT-L | Reserve +0.65pt and photo holdout +0.67pt (p = 0.004) locally; leaderboard −0.25pt. Closed. |
| SigLIP 2 ViT-L/16 | 0.94268 at base stage; gate failed by 2.7pt. |
| Web-SSL DINO ViT-L (uncurated web data) | 0.94236 at base stage; gate failed by 2.8pt — DINOv2's recipe, different data. |
| Five more EVAP blends | Moved only 42–54 rows from the best file, so they could only ever read as ties. Not submitted. |

### Two process lessons

**Reserve the evaluation set before training, on disk, fingerprinted.** Three separate bugs
came from letting training-side logic decide what counted as held out — most seriously, a
`SEED` change silently moved the train/validation split so an external diagnostic scored a
model on images it had trained on (86% overlap) and **reversed a conclusion** about
resolution. `_make_eval_holdout.py` now writes the reserve first and the training draw asserts
it never touches it.

**A collapse detector needs both of its clauses.** The distillation-collapse signal is "best
epoch <= 2 **and** validation falling materially". The implementation tested only the first
clause and raised false alarms on two healthy runs. Fixed to require both, and it correctly
reclassifies the DINOv2 run (best epoch 2, but EMA fell only 0.43pt against a 1.00pt
threshold) as healthy — that run went on to score 0.97950.
""")

nb = {'cells': cells,
      'metadata': {'kernelspec': {'display_name': 'Python 3', 'language': 'python',
                                  'name': 'python3'},
                   'language_info': {'name': 'python', 'version': '3.11'}},
      'nbformat': 4, 'nbformat_minor': 5}

with io.open('FIT5215_A1_methodology.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print(f'wrote FIT5215_A1_methodology.ipynb  ({len(cells)} cells: '
      f'{sum(c["cell_type"]=="markdown" for c in cells)} markdown, '
      f'{sum(c["cell_type"]=="code" for c in cells)} code)')
